// Hand-tracing tool for the area borders.
//
// Automatic detection gets the interior borders right but keeps losing the coastline, and
// tuning it further costs more than drawing the last few by hand. This serves the minimap
// with the current polygons drawn on top; redraw the ones that are wrong, leave the rest,
// and it writes lumia-areas.json back in place.
//
//   node trace-server.js        ->  http://<this machine>:4180/
const http = require("node:http");
const fs = require("node:fs");
const path = require("node:path");

const ROOT = __dirname;
const PORT = 4180;
const R = 60.75, OX = 370, OY = 331, UNIT = 0.05;   // lattice <-> pixel, same as the tracer

const toPixel = ([lon, lat]) => [(lon / UNIT) * R + OX, (-lat / UNIT) * R + OY];
const toLonLat = ([x, y]) => [
  +(((x - OX) / R) * UNIT).toFixed(5),
  +((-(y - OY) / R) * UNIT).toFixed(5),
];

const load = () => JSON.parse(fs.readFileSync(path.join(ROOT, "lumia-areas.json"), "utf8"));

function save(edits) {
  const data = load();
  for (const f of data.features) {
    const ring = edits[f.properties.key];
    if (!ring || ring.length < 3) continue;
    const closed = [...ring, ring[0]].map(toLonLat);
    f.geometry.coordinates = [closed];
  }
  // label anchors and the bounding box move with the geometry
  for (const f of data.features) {
    const ring = f.geometry.coordinates[0];
    const xs = ring.map((c) => c[0]), ys = ring.map((c) => c[1]);
    f.properties.center = [
      +((Math.min(...xs) + Math.max(...xs)) / 2).toFixed(5),
      +((Math.min(...ys) + Math.max(...ys)) / 2).toFixed(5),
    ];
  }
  const all = data.features.flatMap((f) => f.geometry.coordinates[0]);
  data.bbox = [
    Math.min(...all.map((c) => c[0])), Math.min(...all.map((c) => c[1])),
    Math.max(...all.map((c) => c[0])), Math.max(...all.map((c) => c[1])),
  ];
  fs.writeFileSync(path.join(ROOT, "lumia-areas.json"), JSON.stringify(data, null, 1));
  fs.writeFileSync(path.join(ROOT, "lumia-areas.js"),
    "// Generated by trace-areas.py / trace-server.js — do not edit by hand.\n" +
    "var LUMIA = " + JSON.stringify(data, null, 1) + ";\n" +
    'if (typeof module !== "undefined") module.exports = { LUMIA };\n');
  return data.features.length;
}

http.createServer((req, res) => {
  if (req.method === "POST" && req.url === "/save") {
    let body = "";
    req.on("data", (c) => (body += c));
    req.on("end", () => {
      try {
        const n = save(JSON.parse(body));
        res.writeHead(200, { "content-type": "application/json" });
        res.end(JSON.stringify({ ok: true, areas: n }));
        console.log("saved", new Date().toLocaleTimeString());
      } catch (err) {
        res.writeHead(500); res.end(String(err));
      }
    });
    return;
  }

  if (req.url === "/areas") {
    const data = load();
    const out = {};
    for (const f of data.features) {
      out[f.properties.key] = {
        name: f.properties.name,
        ring: f.geometry.coordinates[0].slice(0, -1).map(toPixel),
      };
    }
    res.writeHead(200, { "content-type": "application/json" });
    res.end(JSON.stringify(out));
    return;
  }

  const file = req.url === "/" ? "trace.html" : req.url.slice(1).split("?")[0];
  const full = path.join(ROOT, file);
  if (!full.startsWith(ROOT) || !fs.existsSync(full)) { res.writeHead(404); res.end("no"); return; }
  const type = { ".html": "text/html", ".png": "image/png", ".json": "application/json" }[path.extname(full)];
  res.writeHead(200, { "content-type": type || "application/octet-stream" });
  fs.createReadStream(full).pipe(res);
}).listen(PORT, "0.0.0.0", () => console.log(`tracing on http://0.0.0.0:${PORT}/`));
